# Copyright 2021-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

name: Build And Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # NOTE: If we decide to archive the build products we should build with RelWithDebInfo instead.
  BUILD_TYPE: Debug

jobs:
  build:
    # Build/test on Ubuntu Linux + GCC, macOS + Apple Clang, Windows + MSVC.
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

#### BUILD

    - name: Create Build Environment
      # Create a build directory, as our working directory for all subsequent commands
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # "Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12"
      if: runner.os != 'Windows'
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLITECORE_SANITIZE=ON

    - name: Build
      # Use cmake to build -- this will invoke `make` on Linux/Mac, Visual Studio on Windows.
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $env:BUILD_TYPE

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ${{github.workspace}}/build

